### ISSUE TITLE
Halp Halp!

### ISSUE THREAD

**Issue by MrNinja008** [UltraFlappy/ShulkerBox#21]
Players can keep shullker box in protected zones like land claims / worldguard etc i dont think this issue from claims and worldguard Plugin side.

**Comment by UltraFlappy** [comment]
Can you explain in more detail?

**Comment by MrNinja008** [comment]
> Can you explain in more detail?

Players can able to place shulker in protected zone I am using world guard to protect my lobby from Griff and they can't place anything in lobby but they can able to place skulker

**Comment by UltraFlappy** [comment]
![Screenshot_20210621-150401543](https://user-images.githubusercontent.com/60063027/122728390-4b03b080-d2a2-11eb-919e-ab476983109a.jpg)

I think it's other plugin side
